### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by artz** [vuetifyjs/webpack#5]
The latest version of `vuetify` caused a regression, as it is now looking for the `REQUIRED_VUE` env var which was not previously set. 

Adding it to the `*.env.js` file resolves the issue:

```
module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  REQUIRED_VUE: '"2.0"'
})
```
Are these webpack configs outdated with the new release?

**Comment by KaelWD** [comment]
No, it's a bug with vuetify. We're already tracking it, should be resolved shortly.

**Comment by ArnyS** [comment]
what should i change?

**Comment by KaelWD** [comment]
None of them, it was fixed in 1.0.3

**Comment by ArnyS** [comment]
@KaelWD please, what should i do in case of vue init vuetifyjs/webpack-ssr installation method?

**Comment by KaelWD** [comment]
update to 1.0.3

**Comment by smxsm** [comment]
I still have that error with 1.0.3. ... adding it to ```*.env.js``` still fixes it ... anything I need to/could check / do?

**Comment by smxsm** [comment]
If I change the component imports from "vuetify/src/..." to "vuetify/es5/..." in my a-la-carte project it works without "REQUIRED_VUE", thx @KaelWD for the Discord support :)
